Kino 5
OrKelly/cinema-backend pull request #1
Opened 2024-11-26 09:56 UTC by mrlawsuit

Создал базовую модель для БД
Создал модели halls, places, rows, film_sessions, films, genres для БД
Создал Enumы для модели films

2024-11-27 15:44 UTC, OrKelly requested changes

2024-11-27 15:44 UTC, OrKelly commented on apps/cinema/models/halls.py
> +    title: Mapped[str] = mapped_column(String(45))
Лучше использовать просто id. Везде и ниже лучше поменять, чтоб везде все было единообразно и нам проще было делать запросы. P.S. в миксинах БД есть IdMixin или что такое, от него можно просто унаследоваться и всё

2024-11-27 15:44 UTC, OrKelly commented on apps/films/models/films.py
> +    genre_id: Mapped[int] = mapped_column(
Cвязь с genre через many to many промежуточную таблицу. Через foreign key у фильма будет только один жанр

2024-11-27 15:44 UTC, OrKelly commented on apps/films/models/films.py
> +
Еще лучше бы добавить date_rent_start и date_rent_end. Нам будет удобнее получать текущие фильмы, и выпускать их в анонс, чем аннотировать сеансы. Так же и с закрытием, проще будет таской цеплять фильмы с истекшой датой аренды и снимать их с афишы

2024-11-27 15:44 UTC, OrKelly commented on apps/cinema/models/__init__.py
Импортни все модельки в init. В другом пакете, films сделай также. P.S. линтер будет ругаться, на каждый строчке поставь # noqa: и номер ошибки, которую он выдает. F401 вроде. Я где то оставлял уже такое, глянь

2024-11-29 09:04 UTC, SwedL commented on apps/cinema/models/rows.py
> +        ForeignKey('rows.id_row', onupdate='CASCADE', ndelete='CASCADE'),
Олег здесь вроде пропущен символ "o" ondelete

2024-11-29 09:44 UTC, SwedL approved these changes

2024-11-29 19:18 UTC, OrKelly approved these changes

2024-11-29 19:19 UTC, merged