Kino 13
OrKelly/cinema-backend pull request #12
Opened 2024-12-21 12:46 UTC by mrlawsuit

Добавление ручки фильмов

2024-12-22 07:43 UTC, OrKelly requested changes

2024-12-22 07:43 UTC, OrKelly commented on apps/films/services/validation.py
> +            raise StartDateIncorrectException
Дата проката может быть позже сегодняшнего дня. У нас же будут и анонсы. Она скорее не может быть раньше сегодняшнего дня. И лучше назвать файл validators

2024-12-22 07:43 UTC, OrKelly commented on apps/films/use_cases/poster_create.py
> +        return film_data
юз кейс излишен. Прокинь зависимость к s3 в самом юз кейсе фильмов, и сделай всю логику там через отдельный метод. У s3 есть метод get_object, он возвращает и само содержимое и его url. Там возвращается класс респонса, у которого есть метод url (но там хранится только путь относительного самого минио, то есть только бакет и сам файл).

2024-12-22 07:43 UTC, OrKelly commented on api/v1/films/handlers/films.py
> +    film_data: FilmAddSchema,
А не получится постер прокинуть в саму схему?

2024-12-22 07:43 UTC, OrKelly commented on apps/films/use_cases/validation.py
> +        return await self.validator.validate(film_data)
Валидаторы можно в сервис закинуть, юз кейс не очень подходит для этого слоя логики. BaseValidatorFilmService и т.д. И как я понял, ты хочешь принимать туда сразу несколько валидаторов. Сделай тогда так

```
class ComposedFilmValidatorService(BaseFilmValidatorService):
    validators: Iterable[BaseFilmValidatorService]

    async def validate(self, ...) -> None:
           for validator in self.validators:
                 await self.validator.validate(...)
```
                 
  Пример есть в регистрации, можешь там глянуть

2024-12-22 07:43 UTC, OrKelly commented on apps/films/use_cases/validation.py
> +        return await self.validator.validate(film_data)
Или если все таки валидатор будет один, то тогда в целом не имеет смысла делать то. что я описал выше. Оставь те валидаторы с датой, и все. Зависимость к базовому классу валидаторов прокинь и хватит этого,а юз кейс вообще убери

2024-12-22 07:43 UTC, OrKelly commented on apps/films/services/validation.py
> +    def validate(self, film_data: dict[str, any]) -> None: ...
BaseFilmValidatorService

2024-12-22 07:43 UTC, OrKelly commented on tests/films/test_api.py
> +        return "api/v1/films/add"
api/v1/films

2024-12-22 07:43 UTC, OrKelly commented on tests/films/test_api.py
> +        date_rent_start = datetime.now(UTC) - timedelta(4)
Поправь тогда еще даты в тесте, я уже писал выше, что дата старта наоборот, должна быть либо сегодня, либо позже

2024-12-28 18:56 UTC, mrlawsuit commented on api/v1/films/handlers/films.py
> +    film_data: FilmAddSchema,
нет, его BaseModel пайдентика не понимает

2025-01-07 16:27 UTC, OrKelly commented on api/v1/films/schemas/films.py
> +        )
https://stackoverflow.com/questions/60127234/how-to-use-a-pydantic-model-with-form-data-in-fastapi

2025-01-07 16:28 UTC, OrKelly commented on apps/films/use_cases/film_create.py
> +
Не забываем про DI. Мы зависим от абстракции, т.е. от базового класса s3 хранилища, а не его конкретной реализации

2025-01-07 16:29 UTC, OrKelly commented on apps/films/use_cases/film_create.py
> +        return self.poster_creator.get_object(poster_filepath).url
Добавил метод для сохранения файла сразу из памяти, без необходимости сначала сохранять его на локальном диске

2025-01-07 16:30 UTC, OrKelly commented on apps/films/use_cases/film_create.py
> -class BaseCreateFilmUseCase:
Базовый класс тут излишен, т.к. мы не будем менять реализацию создания фильма, в отличии от той же регистрации/аутентификации

2025-01-07 16:31 UTC, OrKelly commented on core/containers.py
> +    container.register(BaseFilmValidatorService, FilmRentDatesValidatorService)
Нет нужды в ComposedValidator, т.к. у нас только один валидатор в настоящее время. Composed аккамулириует в себе несколько валидаторов и использует их по очереди.

2025-01-07 16:32 UTC, OrKelly commented on core/storages/s3/utils.py
> +        raise e
Контекстный менеджер, который удаляет файл из минио, если было вызвано исключение где либо. Чтобы файл не висел без дела

2025-01-14 07:00 UTC, merged