Сконфигурировать логгирование
OrKelly/cinema-backend pull request #8
Opened 2024-12-19 10:49 UTC by prStudentka

[Сконфигурировать логгирование](https://educationplatform.atlassian.net/browse/KINO-2)

2024-12-20 14:25 UTC, OrKelly requested changes

2024-12-20 14:25 UTC, OrKelly commented on core/loggings/base.py
> +    """
В одиночном числе. BaseLogging

2024-12-20 14:25 UTC, OrKelly commented on core/loggings/base.py
> +    def get_full_format(self): ...
Не не. Эти методы не пойдут в абстракцию, т.к. это методы конкретной реализации. К примеру, потом мы захотим логировать все через ELK. Там не будет этих методов, там они попросту ненужны, но их нужно будет реализовать. Это нарушение сразу двух принципов солида: I и D.  Точно таже история и с level и format, module_name можно оставить. Тут должны быть шаблоны методов записи лога и еще что то в таком же роде, а эти методы нужно спустить в конкретный класс логгирования

2024-12-20 14:25 UTC, OrKelly commented on core/middlewares/__init__.py
> +from .logAPI import LoggingAPIMiddleware
log_api. По snake_case

2024-12-21 11:53 UTC, prStudentka commented on core/loggings/base.py
> +    def get_full_format(self): ...
Из абстрактного класса эти методы и level, format убираю? 
А в абстрактном классе будет  module_name и ... шаблоны методов записи ( info, debug, error, ..) так? или что является шаблоном?

2024-12-22 07:12 UTC, OrKelly commented on core/loggings/base.py
> +    def get_full_format(self): ...
В абстрактном классе должен быть шаблон методов, которые в обязательном порядке должны реализовать классы наследники. Логгирование происходит не только с помощью файлов. Да, примерно такие методы и должны быть. методы и level с format это уже конкретная реализация логгирования основанного на записи в файл (стандартная либа питона, loguru)

2024-12-27 17:13 UTC, closed without merging